spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: diwanshu
    password: diwanshu
    driver-class-name: org.postgresql.Driver
  jpa:

    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        format_sql: true;
        show_sql: true;
    database-platform: org.hibernate.dialect.PostgreSQLDialect